# Generated by Django 3.1 on 2020-11-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201031_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imange',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
