# Generated by Django 3.1 on 2020-11-02 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_imange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imange',
            new_name='image',
        ),
    ]
